# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'IOS-APP' do

pod 'j2objc-common-debug', :configuration => ['Debug'], :path => '/Users/lauris/dev/ideaspace/j2objc-multi/common/build'
pod 'j2objc-common-release', :configuration => ['Release'], :path => '/Users/lauris/dev/ideaspace/j2objc-multi/common/build'
end

target 'IOS-APPTests' do

pod 'j2objc-common-debug', :configuration => ['Debug'], :path => '/Users/lauris/dev/ideaspace/j2objc-multi/common/build'
pod 'j2objc-common-release', :configuration => ['Release'], :path => '/Users/lauris/dev/ideaspace/j2objc-multi/common/build'
end
